
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: clusters.metal.harvesterhci.io
spec:
  group: metal.harvesterhci.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: ClusterStatus
      type: string
    - jsonPath: .status.token
      name: ClusterToken
      type: string
    - jsonPath: .status.clusterAddress
      name: ClusterAddress
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Cluster is the Schema for the clusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterSpec defines the desired state of Cluster
            properties:
              clusterConfig:
                properties:
                  configURL:
                    type: string
                  nameservers:
                    items:
                      type: string
                    type: array
                  sshKeys:
                    items:
                      type: string
                    type: array
                type: object
              imageURL:
                type: string
              nodes:
                items:
                  properties:
                    addressPoolReference:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                      - name
                      - namespace
                      type: object
                    inventoryReference:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                      - name
                      - namespace
                      type: object
                    staticAddress:
                      type: string
                  required:
                  - addressPoolReference
                  - inventoryReference
                  type: object
                type: array
              version:
                type: string
              vipConfig:
                properties:
                  addressPoolReference:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                  staticAddress:
                    type: string
                required:
                - addressPoolReference
                type: object
            required:
            - nodes
            - version
            - vipConfig
            type: object
          status:
            description: ClusterStatus defines the observed state of Cluster
            properties:
              clusterAddress:
                type: string
              status:
                type: string
              token:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
