{{- if .Values.controller.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ .Values.controller.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.controller.roleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.name }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
