{{- if .Values.server.deploy -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.server.name }}
  name: {{ .Values.server.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: {{ .Values.server.service.port }}
    protocol: TCP
    targetPort: {{ .Values.server.deployment.portName }}
  selector:
    app: {{ .Values.server.name }}
{{- end -}}
