#!/bin/bash
set -e

cd $(dirname $0)/..
go fmt ./...
go vet ./...
go generate ./...
GOARCH=amd64 CGO_ENABLED=0 go build -o bin/manager-amd64 .
GOARCH=arm64 CGO_ENABLED=0 go build -o bin/manager-arm64 .
mkdir -p bin