#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

IMAGE=${REPO}/harvester-seeder:${TAG}
DOCKERFILE=package/Dockerfile

docker build -f ${DOCKERFILE} -t ${IMAGE}  .
echo Built ${IMAGE}