#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi


IMAGE=${REPO}/harvester-seeder:${TAG}
DOCKERFILE=package/Dockerfile

buildx build --load \
  -f ${DOCKERFILE} -t ${IMAGE} .
  
echo Built ${IMAGE}