name: Master Build and Publish

on:
  push:
    branches:
      - main
      - release/v*

jobs:
  build-master:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: ${{ github.ref_name }}-head
      push: true
    secrets: inherit
