name: Pull Request Build

on:
  pull_request:

jobs:
  build-pr:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: pull-${{ github.event.number }}
      push: false
    secrets: inherit
