on:
  workflow_call:
    inputs:
      refs:
        required: false
        type: string
      release-tag-name:
        required: true
        type: string
      push:
        required: true
        type: boolean
env:
  PLATFORMS: linux/amd64,linux/arm64
  imageName: "harvester-seeder"
  dockerfile: "package/Dockerfile"

jobs:
  dapper-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code without refs
        if: ${{ inputs.refs == '' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout code with refs
        if: ${{ inputs.refs != '' }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ inputs.refs }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Run dapper
        run: make ci

      - name: Resolve registries
        id: resolve
        uses: harvester/harvester-actions/actions/resolve-registries@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
        with:
          release-tag-name: ${{ inputs.release-tag-name }}
          is-release: ${{ github.event_name == 'release' && github.event.action == 'published' }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${RELEASE_TAG_NAME#prime-}" >> "$GITHUB_ENV"
        env:
          RELEASE_TAG_NAME: ${{ inputs.release-tag-name }}

      - name: Login to Docker Hub
        id: login-docker
        if: ${{ inputs.push == true && steps.resolve.outputs.use-docker-io == 'true' }}
        uses: harvester/harvester-actions/actions/login-docker-hub@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

      - name: Publish public ${{ env.imageName }} image
        if: ${{ inputs.push == true && steps.resolve.outputs.use-docker-io == 'true' }}
        uses: harvester/harvester-actions/actions/publish-public-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
        with:
          context: .
          dockerfile: ${{ env.dockerfile }}
          image: ${{ env.imageName }}
          tag: ${{ env.IMAGE_TAG }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-docker.outputs.registry }}
          repository: ${{ steps.login-docker.outputs.repository }}

      - name: Login to Staging Registry
        id: login-staging
        if: ${{ inputs.push == true && steps.resolve.outputs.use-staging == 'true' }}
        uses: harvester/harvester-actions/actions/login-staging-registry@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

      - name: Publish staging ${{ env.imageName }} image
        if: ${{ inputs.push == true && steps.resolve.outputs.use-staging == 'true' }}
        uses: harvester/harvester-actions/actions/publish-prime-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
        with:
          context: .
          dockerfile: ${{ env.dockerfile }}
          image: ${{ env.imageName }}
          tag: ${{ env.IMAGE_TAG }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-staging.outputs.registry }}
          repository: ${{ steps.login-staging.outputs.repository }}

      - name: Login to Prime Registry
        id: login-prime
        if: ${{ inputs.push == true && steps.resolve.outputs.use-prime == 'true' }}
        uses: harvester/harvester-actions/actions/login-prime-registry@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main

      - name: Publish prime ${{ env.imageName }} image
        if: ${{ inputs.push == true && steps.resolve.outputs.use-prime == 'true' }}
        uses: harvester/harvester-actions/actions/publish-prime-image@a6fc1cfb81904c08e2267675fd5ac7b11a5092a9 # main
        with:
          context: .
          dockerfile: ${{ env.dockerfile }}
          image: ${{ env.imageName }}
          tag: ${{ env.IMAGE_TAG }}
          platforms: ${{ env.PLATFORMS }}
          registry: ${{ steps.login-prime.outputs.registry }}
          repository: ${{ steps.login-prime.outputs.repository }}
