---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seeder.fullname" . }}-manager-role
rules:
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - update
    - watch
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
- apiGroups:
    - ""
  resources:
    - configmaps
    - services
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - bmc.tinkerbell.org
  resources:
    - machines
    - jobs
    - tasks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - bmc.tinkerbell.org
  resources:
    - machines/status
    - jobs/status
    - tasks/status
  verbs:
    - get
    - create
    - patch
    - update
- apiGroups:
    - metal.harvesterhci.io
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - tinkerbell.org
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - validatingwebhookconfigurations
  verbs:
    - get
    - watch
    - list
    - update
    - create
    - delete
    - patch
- apiGroups:
    - apiregistration.k8s.io
  resources:
    - apiservices
  verbs:
    - get
    - watch
    - list
    - update
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seeder.fullname" . }}-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
