---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "seeder.fullname" . }}-manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machines
  - jobs
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - machines/status
  - jobs/status
  - tasks/status
  verbs:
    - get
    - create
    - patch
    - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - addresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - addresspools/finalizers
  verbs:
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - addresspools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - metal.harvesterhci.io
  resources:
  - inventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tinkerbell.org
  resources:
  - hardwares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
    - update
    - patch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seeder.fullname" . }}-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
