apiVersion: v1
kind: Service
metadata:
  name: "harvester-seeder"
  labels:
    {{- include "seeder.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9443
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "seeder.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: harvester-seeder-endpoint
  labels:
    {{- include "seeder.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: endpoint
      protocol: TCP
      name: endpoint
  selector:
    {{- include "seeder.selectorLabels" . | nindent 4 }}
